# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-21 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u59d3\u540d')),
                ('age', models.CharField(max_length=32, verbose_name='\u5e74\u9f84')),
                ('email', models.EmailField(max_length=32, verbose_name='\u90ae\u7bb1')),
                ('company', models.CharField(max_length=32, verbose_name='\u516c\u53f8')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.IntegerField(verbose_name='\u4ed8\u8d39\u91d1\u989d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4ed8\u8d39\u65f6\u95f4')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Customer', verbose_name='\u5173\u8054\u5ba2\u6237')),
            ],
        ),
    ]
