# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-21 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u83dc\u5355')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u56fe\u6807')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('url', models.CharField(max_length=32, verbose_name='\u6743\u9650')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu')),
            ],
            options={
                'verbose_name': '\u6743\u9650\u8868',
                'verbose_name_plural': '\u6743\u9650\u8868',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u89d2\u8272\u540d\u79f0')),
                ('permissions', models.ManyToManyField(blank=True, to='rbac.Permission', verbose_name='\u89d2\u8272\u6240\u62e5\u6709\u7684\u6743\u9650')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='\u7528\u6237\u6240\u62e5\u6709\u7684\u89d2\u8272')),
            ],
        ),
    ]
