# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-22 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='\u7236\u6743\u9650'),
        ),
    ]
